### ISSUE TITLE
Update DNS PowerShell to DSC

### ISSUE THREAD

**Issue by justin-p** [justin-p/ansible-role-pdc#10]
```
- name: Check for xDnsServer Powershell module
  win_psmodule:
    name: xDnsServer
    state: present

- name: Configure DNS Forwarders
  win_dsc:
    resource_name: xDnsServerSetting
    Name: DNSServerProperties
    NoRecursion: false
    Forwarders:
      - "8.8.8.8"
      - "8.8.4.4"
```
